name: Python CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t my-flask-app .

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version

    - name: Log in to Azure
      run: |
        echo '${{ secrets.AZURE_CREDENTIALS }}' > credentials.json
        az login --service-principal --subscription <subscription-id> --tenant <tenant-id> --credential @credentials.json
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS_TENANT_ID }}
        
    - name: Deploy to Azure App Service
      run: |
        az webapp up --name my-flask-app --resource-group my-resource-group
