name: Python CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        echo "Building the application"
        python3 app.py



    - name: Deploy
      if: success()   # Deploy only if tests pass
      run: |
        echo "Deploying the application"
        # Add deployment commands here (e.g., SSH to remote server and copy files)